baseURL = "https://blog.jeffreysummers.me"
languageCode = "en-us"
title = "Jeffrey Summers' blog"
theme = "minimal-esque"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Jeffrey Summers"
    description = "musings + snippets ( of ) life"
    githubUsername = "obscuredetour"
    accent = "#318c63"
    showBorder = true
    backgroundColor = "#1d1d1d"
    font = "IBM Plex Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "tomorrow-night"
    highlightLanguages = ["go", "js", "html", "css", "sass"]

[[menu.main]]
    url = "https://www.jeffreysummers.me"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

# [[menu.icon]]
#     url = "https://github.com/username/"
#     name = "github"
#     weight = 2

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
